# Generated by Django 4.0.3 on 2022-04-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='certificate_image',
            field=models.ImageField(blank=True, upload_to='doctor_certificate/'),
        ),
    ]
