# Generated by Django 4.0.3 on 2022-04-07 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctortimeslot_doctor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('day', 'start_time', 'end_time', 'half_time')},
        ),
    ]
